event/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
#from .models import User
from .forms import LoginForm, RegisterForm
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from event.models import User
from . import db

# create a blueprint
bp = Blueprint('auth', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()

    if (register_form.validate_on_submit() == True):
        # get username, password and email from the form
        image = request.files[register_form.image.name].read()
        uname = register_form.user_name.data
        pwd = register_form.password.data
        email_id = register_form.email_id.data
        street_number = register_form.street_number.data
        street = register_form.street.data
        city = register_form.city.data
        state = register_form.state.data
        post_code = register_form.post_code.data

        # check if a user exists
        u1 = User.query.filter_by(name=uname).first()
        if u1:
            flash('User name already exists, please login.')
            return redirect(url_for('auth.login'))
        # don't store the password - create password hash
        pwd_hash = generate_password_hash(pwd)
        # create a new user model object
        new_user = User(image=image, name=uname, password_hash=pwd_hash, email=email_id,
                        street_number=street_number, street=street, city=city, state=state, post_code=post_code)
        db.session.add(new_user)
        db.session.commit()
        # commit to the database and redirect to HTML page
        return redirect(url_for('auth.login'))
    # the else is called when there is a get message
    else:
        return render_template('user.html', form=register_form, heading='Register')


# this is the hint for a login function
@bp.route('/login', methods=['GET', 'POST'])
def login():  # view function
    login_form = LoginForm()
    error = None
    if (login_form.validate_on_submit() == True):
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        if u1 is None:
            error = 'Incorrect username or password'
        # check password hash
        elif not check_password_hash(u1.password_hash, password):
            error = 'Incorrect username or password'
        if error is None:
            login_user(u1)
            # this gives the url from where the login page was accessed
            nextp = request.args.get('next')
            if nextp is None or not nextp.startswith('/'):
                return redirect(url_for('main.index'))
            return redirect(nextp)
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    # this gives the url from where the login page was accessed
    nextp = request.args.get('next')
    if nextp is None or not nextp.startswith('/'):
        return redirect(url_for('main.index'))
    return redirect(nextp)

event/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash

from . import app
from .models import Event, Artist, EventStatus, Venue

bp = Blueprint('main', __name__)


@app.context_processor
def inject_vars():
    return {"StatusColours": ["bg-primary", "bg-info", "bg-warning", "bg-danger"],
            "StatusText": ["Open", "Unpublished", "Sold-out", "Cancelled"],
            "genres": Event.query.join(Artist).filter(Event.status != EventStatus.unpublished).with_entities(Artist.genre).distinct().all(),
            "artists": Artist.query.all()}


@bp.route('/')
def index():
    events = Event.query.filter(Event.status != EventStatus.unpublished).all()
    venues = Venue.query.all()
    return render_template('index.html', events=events, venues=venues)


@bp.route('/genre/<genre>')
def genre(genre):

    filtered_events = Event.query.join(Artist, Artist.id == Event.artist)\
        .filter(Artist.genre.contains(genre))\
        .filter(Event.status != EventStatus.unpublished).all()

    return render_template('events_list.html', page_title=f"{genre} Performances",
                           events=filtered_events)


@bp.route('/search')
def search():
    if query := request.args.get('search'):
        if len(query) >= 3:
            
            search_term = f"%{query}%"

            results = Event.query.join(Artist, Artist.id == Event.artist)\
                .join(Venue, Venue.id == Event.venue)\
                .filter((Artist.name.ilike(search_term)
                        | Artist.genre.ilike(search_term)
                        | Event.name.ilike(search_term)
                        | Venue.name.ilike(search_term))
                        & (Event.status != EventStatus.unpublished)).all()

            return render_template('events_list.html', page_title=f"Search results for '{query}'",
                                   events=results)

        else:                        
            flash("Search must 3 characters or more.")
            return redirect(url_for('main.index'))

    else:
        flash("Please enter a search term.")
        return redirect(url_for('main.index'))

event/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ title }}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>


    <link rel="apple-touch-icon" sizes="180x180" href="static/img/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="static/img/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="static/img/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="static/img/favicon_io/site.webmanifest">
    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %} {% if messages %}
        <div class="col-11 col-sm-6 col-md-4 col-lg-3 col-xl-2 toast-flash toast-flash">
            {% for message in messages %}
                <!--loop through the messages-->
                <div class="alert alert-info">{{ message }}</div>
                <!--display as alert-->
            {% endfor %}
        </div>
    {% endif %} {% endwith %}
</head>

<body class="d-flex flex-column">
<noscript>
    <div class="alert alert-danger text-center m-0 rounded-0" role="alert">
        <i class="bi bi-exclamation-triangle-fill"></i> Warning, JavaScript is Disabled!
        Some features of this site requires JavaScript to be
        <a class="text-dark" href="https://www.enable-javascript.com/">enabled</a>.
    </div>
</noscript>

<header>
    <nav class="navbar navbar-expand-lg glow">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='img/Elevental-logos/Elevental-rectangle_white.svg') }}"
                     alt="Logo"
                     width="150" height="30"
                     class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex flex-wrap mt-2 mt-lg-auto me-auto">
                    <ul class="navbar-nav flex-row flex-wrap align-self-center">
                        <li class="nav-item">
                            <a class="nav-link active p-2" aria-current="page"
                               href="{{ url_for('main.index') }}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link p-2 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Artists & Band
                            </a>
                            <ul class="dropdown-menu position-absolute">
                                {% for artist in artists %}
                                    <li><a class="dropdown-item"
                                           href="{{ url_for('artist.get_artist' , artist_id = artist.id) }}">{{ artist.name }}</a>
                                    </li>
                                {% endfor %}
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link p-2 dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Genres
                            </a>
                            <ul class="dropdown-menu position-absolute dropdown-menu-end dropdown-menu-lg-start">
                                {% for genre in genres %}
                                    <li><a class="dropdown-item"
                                           href="{{ url_for('main.genre',genre=genre[0]) }}">{{ genre[0] }}</a></li>
                                {% endfor %}                                
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('event.all') }}">View All Events</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="d-flex flex-row flex-wrap align-items-end">
                    <form class="d-flex mx-2 mx-lg-0" action="{{ url_for('main.search') }}" role="search">
                        <input type="text" name="search" class="form-control me-1" id="SearchForm"
                               placeholder="Search Artist or Location"
                               aria-label="Search">
                        <button type="submit" class="btn btn-primary ms-sm-2 bi bi-search" title="Search"></button>
                    </form>
                    <div class="dropdown ms-2 ms-sm-3 mt-2 mt-sm-0">
                        <button class="btn btn-secondary dropdown-toggle bi bi-person-fill" type="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false" title="Account">&nbsp;
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-sm-start dropdown-menu-lg-end position-absolute">

                            {% if current_user.is_authenticated %}
                                <li><a class="dropdown-item" href="{{ url_for('booking.history') }}">View Tickets &
                                    History</a>
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('event.my_events') }}">My Events</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('venue.create') }}">Create Venue</a>
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('artist.create') }}">Create Artist</a>
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('event.create') }}">Create Event</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                <a class="dropdown-item"
                                   href="{{ url_for('auth.logout', next=request.path) }}">Logout</a>
                            {% else %}
                                <a class="dropdown-item" href="{{ url_for('auth.login', next=request.path) }}">Login</a>
                                <a class="dropdown-item"
                                   href="{{ url_for('auth.register', next=request.path) }}">Register</a>
                            {% endif %}
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>


{% block content %}
{% endblock %}
<footer class="bg-dark text-white text-center py-2 mt-auto">
    <div class="container">
        <div class="row my-1">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="{{ url_for("main.index") }}" class="nav-link px-2 text-muted hover">Home</a></li>
                <li class="nav-item"><a href="{{ url_for("event.all") }}" class="nav-link px-2 text-muted hover">All Events</a></li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a href="{{ url_for("event.create") }}" class="nav-link px-2 text-muted hover">Create an Event</a></li>
                    <li class="nav-item"><a href="{{ url_for("booking.history") }}" class="nav-link px-2 text-muted hover">My Tickets</a></li>
                {% else %}
                    <li class="nav-item"><span class="nav-link px-2 text-muted">🎶🎚️🎛️</span></li>
                    <li class="nav-item"><a href="{{ url_for("auth.login") }}" class="nav-link px-2 text-muted hover">Login</a></li>
                    <li class="nav-item"><a href="{{ url_for("auth.register") }}" class="nav-link px-2 text-muted hover">Register</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="card py-1 mx-5 border-0">
            <div class="footer-acknowledgement pt-3">
                <p3>In the spirit of reconciliation, Elevental acknowledges the Traditional Custodians of Country throughout Australia and their connections to land, water and community. 
                    We pay our respects to Elders past and present, and extend that respect to all Aboriginal and Torres Strait Islander peoples today.</p3>
            </div>
        </div>
    </div>
    
    <p class="mb-1">&copy; Elevental 2022</p>
    <a href="#" class="bi bi-facebook mx-2"></a>
    <a href="#" class="bi bi-instagram mx-2"></a>
    <a href="#" class="bi bi-twitter mx-2"></a>
</footer>
</body>

</html>

event/templates/bookings.html
{% extends 'base.html' %}
{% block content %}
    <header class="container p-4 pb-0">
        <h1>Your tickets</h1>
    </header>
    <main class="container p-4 pt-0">

        {% if not tickets %}
        <div class="col-12">
            <h3 class="text-center text-light">You have no bookings.</h3></div>
        {% endif %}

        {% for booking, event, artist in tickets %}
        <article class="card ticket mb-3">
            <div class="d-md-none row flex-row p-0">
                <div class="col-6">
                    <img class="m-1 rounded-2" src="{{ url_for('img.event', event_id=event.id) }}">
                </div>
                        
                <div class="col-6">
                    <a class="d-flex justify-content-center btn btn-primary py-3 mt-2 me-2" 
                    href="{{ url_for('event.get_event', event_id=event.id) }}">View<br>Event</a>
                </div>                    
            </div>
            <div class="row d-md-none">
                <div class="table-responsive w-100">
                    <table class="table m-0">
                        <thead>
                        <tr class="small">
                            <th scope="col">Event</th>
                            <th scope="col">Artist</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="border-bottom-0 col-md-2">{{ event.name }}</td>
                            <td class="border-bottom-0 col-md-2">{{ artist.name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div> 
            </div>
            <div class="d-flex">
                    <img class="d-none d-md-block align-self-center"
                         src="{{ url_for('img.event', event_id=event.id) }}">
                    <div class="table-responsive w-100 ps-xl-2 ps-xxl-5 ms-xxl-5">
                        <!-- Mobile Display of Table -->
                        <table class="table mb-0 d-md-none">
                            <thead>
                            <tr class="small text-center">
                                <th scope="col">Ticket ID</th>
                                <th scope="col">Qty</th>
                                <th scope="col">Time</th>
                                <th scope="col">Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="border-bottom-0 col-3 text-center">{{ booking.id }}</td>
                                <td class="border-bottom-0 col-2 text-center">{{ booking.tickets }}</td>
                                <td class="border-bottom-0 col-3 text-center">{{ event.datetime.strftime("%I:%M %p") }}</td>
                                <td class="border-bottom-0 col text-center">{{ event.datetime.strftime("%d/%m/%y") }}</td>
                                
                            </tr>
                            </tbody>
                        </table>
                        <!-- Large Display Table -->
                        <table class="table mb-0 d-none d-md-inline">
                            <thead>
                            <tr class="small">
                                <th scope="col">Order ID</th>
                                <th scope="col">Event Name</th>
                                <th scope="col">Artist Name</th>
                                <th scope="col">Qty</th>
                                <th scope="col">Time</th>
                                <th scope="col">Date</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="border-bottom-0 col-md-1">{{ booking.id }}</td>
                                <td class="border-bottom-0 col-md-2">{{ event.name }}</td>
                                <td class="border-bottom-0 col-md-2">{{ artist.name }}</td>
                                <td class="border-bottom-0 col-md-1">{{ booking.tickets }}</td>
                                <td class="border-bottom-0 col-md-1">{{ event.datetime.strftime("%I:%M %p") }}</td>
                                <td class="border-bottom-0 col-md-2">{{ event.datetime.strftime("%d/%m/%y") }}</td>
                                <td class="border-bottom-0 col-md-2">
                                    <a class="btn btn-primary btn-sm d-none d-sm-block"
                                       href="{{ url_for('event.get_event', event_id=event.id) }}">View Event</a>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </article>
        {% endfor %}
    
        <hr>
            <div class="card bg-transparent border-0 text-center">
                <div class="card-body">
                    <a class="h4 d-inline text-decoration-none ms-3" href="{{ url_for('event.all' )}}">
                        Looking for your next incredible event? Click here to find something new!<i class="bi bi-caret-right-fill"></i></a>
                </div>
        

    </main>
{% endblock %}

event/templates/create_venue.html
{% extends "base.html" %} {% import "bootstrap/form.html" as wtf %} {% block
content %}

<div class="container mb-5">
  <div class="card mt-5">
    <div class="d-flex flex-column flex-sm-row text-center border-bottom mt-1 mb-4">
      <h1 class="mx-auto">{{heading}}</h4>
    </div>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %} {% if messages %}
    <!-- check if there are any messages -->
    <div class="container">
      <div class="row mt-3 mb-3">
        <div class="col-6 mx-auto">
          {% for message in messages %}
          <!--loop through the messages-->
          <div>
            <p class="alert alert-info text-center px-3">{{ message }}</p>
          </div>
          <!--display as alert-->
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %} {% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 m-auto">{{wtf.render_form(form)}}</div>

    <!-- When you have login form, then do show the user a link to register -->
    
    <div class="col-md-4 mb-4 mt-1 mx-auto text-center">
    </div>
    
    <div class="mb-4"><p></p></div>
  </div>
</div>
{% endblock %}

event/templates/error.html
{% extends 'base.html' %} {% block content %}
  <div class="text-center mt-5">
    <h1>Error {{error}}<br>{{message}}</h1>
    <p class="mt-4 mb-2">{{sub_message}}</p>
    <p><a href="{{ url_for('main.index') }}">Back</a> to Elevental Home Page.</p>
  </div>
{% endblock %}

event/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <header class="header-gradient text-white text-center p-4">
        <div class="hero-logo">
            <img class="img-fluid glow mh-100"
                 src="{{ url_for('static', filename='img/Elevental-logos/Elevental-rectangle_white.svg') }}" alt="logo">
        </div>
        <hr>
        <h1>Welcome to Elevental{{ " " + current_user.name if current_user.is_authenticated }}!</h1>
        <p1>Elevental allows you to find your favourite artists performances at the best prices while also providing an
            amazing platform for you to discover something new! <br>
            From Dance and 8-bit to Big Band and Jazz, Elevental has you covered for all of your musical performance
            needs!
        </p1>
        <hr>
    </header>

    {# remove this when you have the featured event.id #}
    {% set featured_id = 1 %}

    <div class="card border-0 text-center py-1">
        <h2>Featured Performance</h2>
        <img class="rounded glow mb-1 hero-image align-self-center"
            src="{{ url_for('img.event', event_id=featured_id) }}">
        {# replace featured_id you have the featured event.id #}
    </div>

    <div class="container pb-4">
        <div class="card text-center py-3 border-0 bg-transparent">
            <h2 class="mb-1">{{ events[0].name }}</h2>
            <p class="mb-2">{{ events[0].desc }} on {{ events[0].datetime.strftime("%B %d") }}</p>
            <a class="btn btn-secondary text-white book-button align-self-center hover"
                href="{{ url_for('event.get_event', event_id=1) }}">Buy Tickets</a>
        </div>
    </div>

    



    <main class="container p-4 mb-4">
        <section class="mb-3 text-center">
        <!-- performances section -->
            <section class="mb-3 p-4 bg-dark rounded">
                <h4 class="d-inline" id="performances">Explore Performances</h4>
                <a class="h4 d-inline text-decoration-none ms-3" href="{{ url_for('event.all' )}}">
                    View All<i class="bi bi-caret-right-fill"></i></a>
                <!-- create card for db to populate-->
                <div class="row d-flex justify-content-around mt-4">
                    {% for event in events %}
                        <a href="{{ url_for('event.get_event', event_id=event.id) }}"
                            class="card card-event bg-secondary mx-0 mx-sm-2 my-3 p-0 hover d-flex col-5 col-sm-3 col-md-2">
                            <img class="card-img my-auto h-100 w-auto"
                                src="{{ url_for('img.event', event_id=event.id) }}"
                                alt="Event Image" loading="lazy">
                            <div class="card-img-overlay text-center p-0 d-flex align-content-between flex-column">
                                <span class="text-light h5 position-absolute top-0 bg-dark bg-opacity-50 w-100">{{ event.name }}</span>
                                <span class="text-light h6 position-absolute bottom-0 bg-dark bg-opacity-50 w-100 mb-0">{{ event.datetime.strftime("%B %d") }}</span>
                            </div>

                            <span class="position-absolute status badge {{ StatusColours[event.status.value] }}">
                                {{ StatusText[event.status.value] }}
                            </span>
                        </a>
                    {% endfor %}
                </div>
            </section>

            <!-- genres section -->
            <section class="mb-5 mt-5 p-4 bg-dark rounded">
                <div class="row">
                    <h4 class="d-inline mb-4">Popular Genres</h4>
                </div>

                <div class="row d-flex justify-content-around">
                    {% for genre in genres %}
                    <div class="card border-0 col-md-3 py-4">
                        <a href="{{ url_for('main.genre',genre=genre[0]) }}#performances">
                            <button class="btn btn-primary text-white book-button align-self-center w-75 hover">{{ genre[0] }}</button>
                        </a>
                    </div>
                    {% endfor %}
                </div> 
                
            </section>

            <!-- bands section -->
            <section class="mb-5 mt-5 p-4 bg-dark rounded">
                <div class="row">
                    <h4 class="d-inline mb-4">Browse By Band</h4>
                </div>

                <div class="row d-flex justify-content-around">
                    {% for artist in artists %}
                        <a href="{{ url_for('artist.get_artist' , artist_id = artist.id) }}"
                            class="card card-event bg-secondary mx-0 mx-sm-2 my-3 p-0 hover d-flex col-5 col-sm-3 col-md-2">
                            <img class="card-img my-auto h-100 w-auto"
                                src="{{ url_for('img.artist', artist_id=artist.id) }}"
                                alt="Event Image" loading="lazy">
                            <div class="card-img-overlay text-center p-0 d-flex align-content-between flex-column">
                                <span class="text-light h5 position-absolute top-0 bg-dark bg-opacity-50 w-100">{{ artist.name }}</span>                                                                
                            </div>
                        </a>
                    {% endfor %}
                </div> 
                
            </section>

            <!-- Venue section -->
            <section class="mb-5 mt-5 p-4 bg-dark rounded">
                <div class="row">
                    <h4 class="d-inline mb-4">Browse By Venue</h4>
                </div>

                <div class="row d-flex justify-content-around">
                    {% for venue in venues %}
                        <a href="{{ url_for('venue.get_venue' , venue_id = venue.id) }}"
                            class="card card-event bg-secondary mx-0 mx-sm-2 my-3 p-0 hover d-flex col-5 col-sm-3 col-md-2">
                            <img class="card-img my-auto h-100 w-auto"
                                src="{{ url_for('img.venue', venue_id=venue.id) }}"
                                alt="Event Image" loading="lazy">
                            <div class="card-img-overlay text-center p-0 d-flex align-content-between flex-column">
                                <span class="text-light h5 position-absolute top-0 bg-dark bg-opacity-50 w-100">{{ venue.name }}</span>                                                                
                            </div>
                        </a>
                    {% endfor %}
                </div> 
                
            </section>
    </main>
{% endblock %}

event/templates/user.html
{% extends "base.html" %} {% import "bootstrap/form.html" as wtf %} {% block
content %}

<div class="container mb-5">
  <div class="card mt-5">
    <div class="d-flex flex-column flex-sm-row text-center border-bottom mt-1 mb-4">
      <h1 class="mx-auto">{{heading}}</h4>
    </div>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %} {% if messages %}
    <!-- check if there are any messages -->
    <div class="container">
      <div class="row mt-3 mb-3">
        <div class="col-6 mx-auto">
          {% for message in messages %}
          <!--loop through the messages-->
          <div>
            <p class="alert alert-info text-center px-3">{{ message }}</p>
          </div>
          <!--display as alert-->
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %} {% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 m-auto">{{wtf.render_form(form)}}</div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4 mb-4 mt-1 mx-auto text-center">
      <p>
        New user?
        <a href="{{ url_for('auth.register') }}">Click here to register</a>.
      </p>
    </div>
    {% endif %} {% if heading|lower =='register' %}
    <div class="mb-4"><p></p></div>
    {% endif %}
  </div>
</div>
{% endblock %}